# Generated by Django 5.2.7 on 2025-11-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField()),
                ('user_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_plan', models.JSONField(blank=True, null=True)),
                ('actual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
